{
  config,
  lib,
  ...
}:
let
  aliases = {
    gad = "git add .";
    gc = "git commit -m ";
    gp = "git push";
  };
in
{
  options = {
    git-aliases.enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Enable or disable short git shell aliases (gad/gc/gp)";
    };
  };

  config = lib.mkIf config.git-aliases.enable {
    # picked up by whichever shell home-manager manages (programs.bash/zsh/fish)
    home.shellAliases = aliases;

    # ...but on hosts where ~/.bashrc is hand-written rather than generated by
    # home-manager, the above never reaches bash. Fedora's stock ~/.bashrc
    # sources every file in ~/.bashrc.d, so write them there as well. Inert on
    # hosts whose .bashrc has no such loop.
    home.file.".bashrc.d/10-git-aliases.sh".text =
      lib.concatMapStringsSep "\n" (n: "alias ${n}=${lib.escapeShellArg aliases.${n}}")
        (lib.attrNames aliases)
      + "\n";
  };
}
